# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ff59c5d1ef5b86198509ba5c3c1f33ac8e09d16990bf357273ca9a3062340b989fdd01ffe68ee08ea3bf9ef2b4b21b79ac7e369d48d2bcdd758aa9d19a65b9

test:
  secret_key_base: 5869146151bc23c460603fab0646be3ffaae17d83b87b41ef0b231519202fd39ecbf35609e69963e32666cc3a82546c6f7dbe696c117a8d3392d751f1d91676d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
